# Generated by Django 6.0.6 on 2026-07-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Dress', 'Dress'), ('Shoes', 'Shoes'), ('Bag', 'Bag'), ('Accessory', 'Accessory')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Rainy', 'Rainy'), ('All Season', 'All Season')], max_length=20)),
                ('occasion', models.CharField(choices=[('Casual', 'Casual'), ('College', 'College'), ('Office', 'Office'), ('Party', 'Party'), ('Wedding', 'Wedding')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
