# Generated by Django 6.0.6 on 2026-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='brand',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Dress', 'Dress'), ('Shirt', 'Shirt'), ('T-shirt', 'T-shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Shoes', 'Shoes'), ('Bag', 'Bag'), ('Accessory', 'Accessory')], max_length=20),
        ),
    ]
