# Generated by Django 6.0.6 on 2026-07-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothingitem_brand_alter_clothingitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='ai_confidence',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='last_worn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='pattern',
            field=models.CharField(blank=True, default='Solid', max_length=50),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Streetwear', 'Streetwear'), ('Sport', 'Sport'), ('Traditional', 'Traditional'), ('Ethnic', 'Ethnic'), ('Minimal', 'Minimal'), ('Vintage', 'Vintage')], default='Casual', max_length=30),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='wear_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='occasion',
            field=models.CharField(choices=[('Casual', 'Casual'), ('College', 'College'), ('Office', 'Office'), ('Party', 'Party'), ('Wedding', 'Wedding')], default='Casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Rainy', 'Rainy'), ('All Season', 'All Season')], default='All Season', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL),
        ),
    ]
