# Generated by Django 6.0.6 on 2026-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_clothingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Business Casual', 'Business Casual'), ('Party', 'Party'), ('Streetwear', 'Streetwear'), ('Sporty', 'Sporty'), ('Traditional', 'Traditional'), ('Ethnic', 'Ethnic'), ('Minimalist', 'Minimalist'), ('Vintage', 'Vintage'), ('Elegant', 'Elegant'), ('Bohemian', 'Bohemian')], default='Casual', max_length=30),
        ),
    ]
