# Generated by Django 6.0.6 on 2026-09-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_favoriteoutfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='pattern',
        ),
        migrations.DeleteModel(
            name='FavoriteOutfit',
        ),
    ]
