# Generated by Django 6.0.6 on 2026-09-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_remove_clothingitem_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='purchase_date',
        ),
    ]
