# Generated by Django 6.0.6 on 2026-09-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_remove_clothingitem_estimated_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='last_worn',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='manually_edited',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='wear_count',
        ),
    ]
