# Generated by Django 6.0.6 on 2026-09-27 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_alter_clothingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
