# Generated by Django 6.0.6 on 2026-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Bag', 'Bag'), ('Accessory', 'Accessory'), ('Jewellery', 'Jewellery'), ('Watch', 'Watch'), ('Dress', 'Dress')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('occasion', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.URLField(max_length=500)),
                ('product_link', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
