# Generated by Django 6.0.6 on 2026-09-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FashionProduct',
        ),
    ]
