# Generated by Django 6.0.6 on 2026-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Bag', 'Bag'), ('Watch', 'Watch'), ('Belt', 'Belt'), ('Jewellery', 'Jewellery'), ('Accessory', 'Accessory')], max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('style', models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Streetwear', 'Streetwear'), ('Traditional', 'Traditional'), ('Sport', 'Sport'), ('Minimal', 'Minimal')], max_length=30)),
                ('occasion', models.CharField(choices=[('College', 'College'), ('Office', 'Office'), ('Party', 'Party'), ('Wedding', 'Wedding'), ('Casual', 'Casual')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image', models.ImageField(upload_to='products/')),
                ('buy_link', models.URLField()),
                ('store', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
